version: '3'

services:
  # Servicio para el frontend React
  frontend:
    image: node:21-alpine3.18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000"
    command: sh -c "npm install && npm run build && npm run preview"
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  # Servicio para el backend Express
  backend:
    image: node:21-alpine3.18
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run build && npm start"

  # Servicio para la base de datos PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432" 
      - "5433:5433"  
